// vue/src/VoiceAssistant.vue
<script setup lang="ts">
import { computed, watch } from 'vue';
import { useVoiceClient, type UseVoiceClientOptions } from './useVoiceClient';
import type { ConnectionStatus } from './VoiceClient';

interface Props {
  workspaceKey: string;
  clientId: string;
  clientSecret: string;
  serverUrl?: string;
  appSource?: string;
}

interface Emits {
  (e: 'statusChange', status: ConnectionStatus): void;
  (e: 'transcript', transcript: string): void;
  (e: 'assistantMessage', text: string, done: boolean): void;
  (e: 'functionCall', name: string, args: Record<string, unknown>, callId: string): void;
  (e: 'error', error: Error): void;
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const options: UseVoiceClientOptions = {
  workspaceKey: computed(() => props.workspaceKey),
  clientId: computed(() => props.clientId),
  clientSecret: computed(() => props.clientSecret),
  serverUrl: computed(() => props.serverUrl),
  appSource: computed(() => props.appSource),
  onTranscript: (transcript) => emit('transcript', transcript),
  onAssistantMessage: (text, done) => emit('assistantMessage', text, done),
  onFunctionCall: (name, args, callId) => emit('functionCall', name, args, callId),
  onError: (error) => emit('error', error)
};

const { status, connect, disconnect, sendFunctionResult } = useVoiceClient(options);

// Watch status changes and emit
watch(status, (newStatus) => {
  emit('statusChange', newStatus);
}, { immediate: true });

// Expose methods for parent component
defineExpose({
  connect,
  disconnect,
  sendFunctionResult,
  status
});
</script>

// react/src/VoiceAssistant.tsx
import { forwardRef, useImperativeHandle, useEffect, useRef } from 'react';
import { useVoiceClient, type UseVoiceClientOptions } from './useVoiceClient';
import type { ConnectionStatus } from './VoiceClient';

export interface VoiceAssistantProps {
  workspaceKey: string;
  clientId: string;
  clientSecret: string;
  serverUrl?: string;
  appSource?: string;
  onStatusChange?: (status: ConnectionStatus) => void;
  onTranscript?: (transcript: string) => void;
  onAssistantMessage?: (text: string, done: boolean) => void;
  onFunctionCall?: (name: string, args: Record<string, unknown>, callId: string) => void;
  onError?: (error: Error) => void;
}

export interface VoiceAssistantRef {
  connect: () => Promise<void>;
  disconnect: () => void;
  sendFunctionResult: (callId: string, result: Record<string, unknown>) => void;
  status: ConnectionStatus;
}

export const VoiceAssistant = forwardRef<VoiceAssistantRef, VoiceAssistantProps>(
  function VoiceAssistant(props, ref) {
    const {
      workspaceKey,
      clientId,
      clientSecret,
      serverUrl,
      appSource,
      onStatusChange,
      onTranscript,
      onAssistantMessage,
      onFunctionCall,
      onError
    } = props;

    const options: UseVoiceClientOptions = {
      workspaceKey,
      clientId,
      clientSecret,
      serverUrl,
      appSource,
      onTranscript,
      onAssistantMessage,
      onFunctionCall,
      onError
    };

    const { status, connect, disconnect, sendFunctionResult } = useVoiceClient(options);

    // Track previous status to notify on changes
    const prevStatusRef = useRef(status);
    useEffect(() => {
      if (prevStatusRef.current !== status) {
        prevStatusRef.current = status;
        onStatusChange?.(status);
      }
    }, [status, onStatusChange]);

    // Expose methods via ref
    useImperativeHandle(ref, () => ({
      connect,
      disconnect,
      sendFunctionResult,
      status
    }), [connect, disconnect, sendFunctionResult, status]);

    // This is a headless component - no UI
    return null;
  }
);
